apiVersion: apps/v1
kind: Deployment
metadata:
  name: petshop
spec:
  selector:
    matchLabels:
      app: petshop
  replicas: 1 
  template: 
    metadata:
      labels:
        app: ravipetshop
    spec:
      containers:
      - name:  ravipetshop
        image: ravib007/petshop:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name:  ravipetshop
spec:
  type: LoadBalancer
  selector:
    app:  ravipetshop
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
